
- name: VPC Setup
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws-vpc
    - aws-bastion-host  
    - ec2-stack
  
  tasks:
    - name: Running instances
      ansible.builtin.debug:
        var: managed_instances
    
    - name: Nat Gatway
      ansible.builtin.debug:
        var: natgw_id

    

