
- name: VPC Setup
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws-vpc
    - aws-bastion-host  
    - ec2-stack
  
  tasks:
    - name: Running instances
      ansible.builtin.debug:
        var: managed_instances
    
    - name: Nat Gatway
      ansible.builtin.debug:
        var: natgw_id

    - name: Elastic load balancer
      ansible.builtin.debug:
        var: vpro_elb_id
    
    - name: Store these facts in var file (for termination)
      ansible.builtin.blockinfile:
        mode: 0400
        create: true
        dest: infrastructure-termination/group_vars/service-termination-ids.yml
        block: |
          {{ {
            'natgw_id': natgw_id,
            'managed_instances': managed_instances,
            'vpro_elb_id': vpro_elb_id
          } | to_nice_yaml(indent=2, width=1337) }}
    

