#SPDX-License-Identifier: MIT-0
---
# tasks file for aws-bastion-host
- name: Create key-pair for bastion host
  amazon.aws.ec2_key:
    name: vprofile-key
    region: "{{region}}"
  register: key_out

- name: Save the private key 
  copy:
    content: "{{key_out.key.private_key}}"
    dest: "aws-bastion-host/files/bastion-key.pem"
    mode: 0600
  when: key_out.changed

- name: Create security group for bastion host
  amazon.aws.ec2_group:
    name: bastion-host-sg
    description: bastion-host-sg
    region: "{{region}}"
    vpc_id: "{{vpc_id}}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{MYIP}}"
  register: bastionSG_out

- name: Creating bastion host
  amazon.aws.ec2_instance:
    key_name: vprofile-key
    region: "{{region}}"
    instance_type: "t2.micro"
    image_id: "{{ami_id}}"
    vpc_subnet_id: "{{pub_subnet_ids[0]}}"
    wait: yes
    wait_timeout: 300
    state: "{{insatnce_state}}"
    tags:
      Name: Bastion Host
      Project: Vprofile
      Owner: Devops Team
    exact_count: 1
    security_group: "{{bastionSG_out.group_id}}"
  register: bastion_instance_out
  when: pub_subnet_ids | length > 0