---
- name: Setup Mysql with accounts db and remote login
  hosts: dbsrvgroup
  gather_facts: no
  vars_files:
    - group_vars/dbsvrgrp.yml
  tasks:
    - name: Installing MySqlServices and dependencies
      ansible.builtin.package:
        name: "{{item}}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: yes
      tags:
        - package
    - name: Start and enable mysql service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
      tags:
        - svc
    
    - name: creating mysql user
      ansible.builtin.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: "*.*:ALL"
        host: "%" #we can login with remote machine
        state: present
    
    - name: create accounts database
      ansible.builtin.mysql_db:
        name: "{{dbname}}"
        state: present
    
    - name: enable remote login to mysql svc
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - restart mysql
      tags:
        - conf
    
  handlers:
    - name: restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted
        