---
- name: Setup mem cache for servers
  hosts: mcsrvgroup
  gather_facts: no
  tasks:
    - name: Install memcache
      ansible.builtin.apt:
        name: memcached
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
        - package
    
    - name: Start and enable memcache
      ansible.builtin.service:
        name: memcached
        state: started
        enabled: yes
      tags:
        - svc
    
    - name: Enable remote login
      ansible.builtin.lineinfile:
        path: /etc/memcached.conf
        regexp: "^ -l "
        line: '-l 0.0.0.0'
        backup: yes
      notify:
        - Restart memcached
      tags:
        - conf
  
  handlers:
    - name: Restart memcached
      ansible.builtin.service:
        name: memcached
        state: restarted
