---
- name: Install & setup RabbitMQ with user
  hosts: rmqsrvgroup
  gather_facts: yes
  tasks:
    # - name: Install erlang repository package
    #  ansible.builtin.apt:
    #    deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    #  tags:
    #    - package
    # - name: Download Erlang Solutions package
    #   ansible.builtin.get_url:
    #     url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    #     dest: /tmp/erlang-solutions.deb
    # - name: Install Erlang Solutions package
    #   ansible.builtin.apt:
    #     deb: /tmp/erlang-solutions.deb
    #     state: present

    # - name: Add an erlang solution public key
    #   ansible.builtin.apt_key:
    #     url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    #     state: present
    #   tags:
    #     - package

    # - name: Install Erlang
    #   ansible.builtin.apt:
    #     name: erlang
    #     update_cache: yes
    #     cache_valid_time: 86400
    #     state: present
    #   tags:
    #     - package
    
    # - name: Add an apt digning key, uses whichever key is at URL
    #   ansible.builtin.apt_key:
    #     url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
    #     state: present
    #   tags:
    #     - package
    
    # - ansible.builtin.apt_repository:
    #     repo: deb https://dl.bintray.com/rabbitmq/debian bionic main
    #     state: present
    #   tags:
    #     - package
    - name: Install required dependencies
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Erlang repository
      apt_repository:
        repo: "ppa:rabbitmq/rabbitmq-erlang"
        state: present
        update_cache: yes

    - name: Add RabbitMQ signing key
      apt_key:
        url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
        state: present

    - name: Download RabbitMQ server deb package
      get_url:
        url: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.12.11/rabbitmq-server_3.12.11-1_all.deb
        dest: /tmp/rabbitmq-server.deb

    - name: Install RabbitMQ server deb
      apt:
        deb: /tmp/rabbitmq-server.deb
      
    - name: install rabbit Mq
      ansible.builtin.apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
      tags:
        - package

    - name: Start and enable rabbit Mq 
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc
    
    - name: Cofig setup
      ansible.builtin.copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf

    - name: Add rabbit mq user
      ansible.builtin.rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_prev: .*
        write_priv: .*
        state: present
        tags: administrator
      notify:
        - Restart RMQ
      tags:
        - conf
    
    - name: Enable the rabbitmq management plugin
      ansible.builtin.rabbitmq_plugin:
        name: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

  handlers:
    - name: Restart RMQ
      ansible.builtin.service:
        name: rabbitmq-server
        state: restarted
