- name: Set host to ip mapping in /etc/hosts file of all the instance of stack
  hosts: all
  tasks:
    - name: Import VPC setup variable
      ansible.builtin.include_vars: group_vars/hostIp.yml
    
    - name: Update the hosts files of all  the servers
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: 
          
          "
          {{web01_ip}} web01

          {{app01_ip}} app01

          {{mc01_ip}} mc01

          {{rmq01_ip}} rmq01

          {{db01_ip}} db01
          "
