---
- name: Setup Nginx svc
  hosts: websrvgroup
  gather_facts: no
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
        update_cache_retries: 86400
      tags:
        - package
    
    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - svc

    - name: Disable nginx default website
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/defaults
        state: absent
      tags:
        - conf

    - name: Deploy web config file
      ansible.builtin.template:
        src: templates/nginxvpro.j2
        dest: /etc/nginx/sites-available/vproapp
      tags:
        - conf
    
    - name: Enable vproapp
      ansible.builtin.file:
        src: /etc/nginx/sites-available/vproapp
        dest: /etc/nginx/sites-enabled/vproapp
        state: link
      notify:
        - Restart nginx
      tags:
        - conf
    
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      tags:
        - svc