#SPDX-License-Identifier: MIT-0
---
# vars file for ec2-stack
ngnix_ami_id: "ami-04f167a56786e4b09"
tomcat_ami_id: "ami-04f167a56786e4b09"
memcache_ami_id: "ami-04f167a56786e4b09"
rmq_ami_id: "ami-04f167a56786e4b09"
mysql_ami_id: "ami-04f167a56786e4b09"

instance_state: "running"